version: "3.8"

services:
  front:
      build:
        context: ./front
        args:
          WORKDIR: $WORKDIR
          # API_URL: "http://localhost:1337/graphql" # 追加
      # コンテナで実行したいコマンド(CMD)
      command: npm start
      volumes:
        - "./front:/$WORKDIR"
      ports:
        - "$FRONT_PORT:3000"
